#!/bin/bash
# Set or toggle Ghostty's horizontal padding — the knob that decides how wide the
# text column is. Alias: `ww`.
#
#   ww       -> toggle between the presets (400 <-> 600)
#   ww 375   -> any width you like, not just a preset
#
# The value is written into ghostty/width-active.conf, which ghostty/config
# includes and .gitignore covers, so changing width never dirties the tracked
# config. One generated file, not one file per width: the payload here is a
# single number, and the symlink-to-a-variant idiom the theme uses would mean a
# committed file for every value you ever tried.
#
# Larger padding = narrower text column. Ghostty re-reads its config on
# cmd+shift+, ; nothing here can force a running window to reload.
set -u

PRESETS=(400 600)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACTIVE="$SCRIPT_DIR/ghostty/width-active.conf"

# Current value, read back from the file we write. Absent or unparseable counts
# as "unset", which the toggle treats as "go to the first preset".
cur=""
[ -f "$ACTIVE" ] && cur="$(sed -n 's/^[[:space:]]*window-padding-x[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*/\1/p' "$ACTIVE" | head -1)"

if [ $# -gt 0 ]; then
    case "$1" in
        -h|--help)
            printf 'usage: ww [WIDTH]   (no argument toggles %s)\n' "${PRESETS[*]}" >&2
            exit 2
            ;;
    esac
    # Any width is allowed, but it still has to be a number — a typo here lands
    # in a config file that ghostty refuses wholesale, taking the theme include
    # down with it.
    case "$1" in
        ''|*[!0-9]*)
            printf 'width.sh: %s is not a number\n' "$1" >&2
            exit 1
            ;;
    esac
    next="$1"
else
    # Toggle: whichever preset is not the current value. Anything else — unset,
    # or an arbitrary width set earlier — lands on the first preset.
    if [ "$cur" = "${PRESETS[0]}" ]; then
        next="${PRESETS[1]}"
    else
        next="${PRESETS[0]}"
    fi
fi

mkdir -p "$(dirname "$ACTIVE")"
cat > "$ACTIVE" <<EOF
# GENERATED by width.sh (alias \`ww\`) — edits here are overwritten.
# Included by ghostty/config; gitignored so width changes never dirty the repo.
window-padding-x = $next
EOF

printf 'ghostty padding-x: %s -> %s  (cmd+shift+, to reload)\n' "${cur:-unset}" "$next"
