# fzf ${ISG_MODE} options — GENERATED by theme/generate.sh.
# Edit theme/palette.sh, not this file.
#
# Read by every fzf on the machine through the opts-active.conf symlink
# ($FZF_DEFAULT_OPTS_FILE, see zsh/.zshenv and toggle_theme.sh) — our pickers,
# fzf-tab, nvim's fzf.vim and the tmux popups alike.
#
# One option per line; `#` starts a comment only at the start of a line, so the
# hex colours below are safe.
#
# bg/fg are -1 (terminal default) on purpose: the terminal is already themed, and
# painting our own background would leave the popup a different shade than the
# pane behind it. The selected row (bg+/fg+) is the one colour that cannot be
# shared between modes — a light selection reads as a glaring white bar on dark —
# so each mode borrows its editor's own nvim `hi Search`. `prompt` likewise:
# black is invisible on dark. Everything else is an ANSI name, which is what
# makes these two files nearly identical.
--preview-window=down:55%
--color=bg:-1,fg:-1,bg+:${ISG_SEL_BG},fg+:${ISG_SEL_FG}
--color=hl:bright-blue,hl+:blue
--color=header:green,info:green,pointer:blue
--color=marker:bright-blue,prompt:${ISG_FZF_PROMPT},spinner:blue
