# Ghostty ${ISG_MODE} theme — GENERATED by theme/generate.sh.
# Edit theme/palette.sh, not this file.
#
# Included through the theme-active.conf symlink, which toggle_theme.sh flips
# from the ~/.config/isg/theme mode file. bg/fg match nvim
# colors/vs_${ISG_MODE}.vim `hi Normal`, so the editor has no seam against the
# terminal it runs in.
#
# palette 0-15 is declared here rather than inherited from Ghostty's bundled
# Catppuccin themes; theme/palette.sh has the values and the reasoning. Indices
# 16-255 keep their xterm defaults, which is why tig can rely on color24.
palette = 0=${ISG_ANSI_0}
palette = 1=${ISG_ANSI_1}
palette = 2=${ISG_ANSI_2}
palette = 3=${ISG_ANSI_3}
palette = 4=${ISG_ANSI_4}
palette = 5=${ISG_ANSI_5}
palette = 6=${ISG_ANSI_6}
palette = 7=${ISG_ANSI_7}
palette = 8=${ISG_ANSI_8}
palette = 9=${ISG_ANSI_9}
palette = 10=${ISG_ANSI_10}
palette = 11=${ISG_ANSI_11}
palette = 12=${ISG_ANSI_12}
palette = 13=${ISG_ANSI_13}
palette = 14=${ISG_ANSI_14}
palette = 15=${ISG_ANSI_15}
background = ${ISG_BG}
foreground = ${ISG_FG}
cursor-color = ${ISG_CURSOR}
# The block cursor inverts what is under it, so the glyph beneath must read as a
# hole punched in the text: cursor-text follows the background automatically.
cursor-text = ${ISG_BG}
