# k9s ${ISG_MODE} skin — GENERATED by theme/generate.sh.
# Edit theme/palette.sh, not this file.
#
# Selected by skins/skin-active.yaml, which toggle_theme.sh flips. k9s reads it
# at launch (config.yaml sets ui.skin: skin-active; reactive is false).
#
# status.addColor and status.killColor are the terminal's own ANSI green and red
# rather than hex roles — the only two places this skin deliberately agrees with
# the ramp every other tool resolves names through.
k9s:
  body:
    fgColor: "${ISG_FG}"
    bgColor: "${ISG_BG}"
    logoColor: "${ISG_ACCENT}"
  prompt:
    fgColor: "${ISG_FG}"
    bgColor: "${ISG_BG}"
    suggestColor: "${ISG_ACCENT_DEEP}"
  info:
    fgColor: "${ISG_FG_DIM}"
    sectionColor: "${ISG_FG}"
  dialog:
    fgColor: "${ISG_FG}"
    bgColor: "${ISG_BG_ALT}"
    buttonFgColor: "${ISG_ON_ACCENT}"
    buttonBgColor: "${ISG_BUTTON_BG}"
    buttonFocusFgColor: "${ISG_ON_ACCENT}"
    buttonFocusBgColor: "${ISG_BUTTON_FOCUS_BG}"
    labelFgColor: "${ISG_ACCENT}"
    fieldFgColor: "${ISG_FG}"
  frame:
    border:
      fgColor: "${ISG_BORDER_UI}"
      focusColor: "${ISG_ACCENT}"
    menu:
      fgColor: "${ISG_FG}"
      keyColor: "${ISG_ACCENT}"
      numKeyColor: "${ISG_ACCENT}"
    crumbs:
      fgColor: "${ISG_CRUMB_FG}"
      bgColor: "${ISG_ACCENT_DEEP}"
      activeColor: "${ISG_ACCENT_BRIGHT}"
    status:
      newColor: "${ISG_ACCENT}"
      modifyColor: "${ISG_NUMBER}"
      addColor: "${ISG_ANSI_2}"
      errorColor: "${ISG_ERROR}"
      highlightColor: "${ISG_WARN}"
      killColor: "${ISG_ANSI_1}"
      completedColor: "${ISG_FG_DIM}"
    title:
      fgColor: "${ISG_FG}"
      bgColor: "${ISG_BG}"
      highlightColor: "${ISG_TITLE_HL}"
      counterColor: "${ISG_ACCENT}"
      filterColor: "${ISG_TYPE}"
  views:
    charts:
      bgColor: "${ISG_BG}"
      defaultDialColors:
        - "${ISG_ACCENT}"
        - "${ISG_ERROR}"
      defaultChartColors:
        - "${ISG_ACCENT}"
        - "${ISG_ERROR}"
    table:
      fgColor: "${ISG_FG}"
      bgColor: "${ISG_BG}"
      cursorFgColor: "${ISG_ON_ACCENT}"
      cursorBgColor: "${ISG_TABLE_CURSOR_BG}"
      markColor: "${ISG_WARN}"
      header:
        fgColor: "${ISG_ACCENT}"
        bgColor: "${ISG_BG}"
        sorterColor: "${ISG_TYPE}"
    xray:
      fgColor: "${ISG_FG}"
      bgColor: "${ISG_BG}"
      cursorColor: "${ISG_XRAY_CURSOR}"
      graphicColor: "${ISG_ACCENT_DEEP}"
      showIcons: false
    yaml:
      keyColor: "${ISG_ACCENT}"
      colonColor: "${ISG_FG_DIM}"
      valueColor: "${ISG_STRING}"
    logs:
      fgColor: "${ISG_FG}"
      bgColor: "${ISG_BG}"
      indicator:
        fgColor: "${ISG_ON_ACCENT}"
        bgColor: "${ISG_BUTTON_BG}"
