" Light (Visual Studio) color scheme for Neovim
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
" Separate from nvim-dark.tpl: this scheme colours Bold/Italic/Underlined and
" declares SpecialComment and Debug, while leaving out MatchParen, Terminal,
" NormalFloat and the treesitter @variable groups. Different files, not just
" different colours.
"
" Colours with a single use stay literal hex — naming a role with one consumer
" buys nothing.

" 'background' first, then `hi clear` — see the same note in vs_dark.vim. Light
" happens to be the background Neovim's defaults were already computed for, but
" relying on that breaks as soon as the theme is flipped the other way.
set background=light
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "vs_light"

" Terminal/ANSI palette — the same 16 slots Ghostty publishes, from
" theme/palette.sh, so this can no longer drift from the terminal.
" baleia.nvim reads these g:terminal_color_* at setup() so captured-pane ANSI
" colors render identically to the live terminal instead of baleia's generic
" defaults. Also fixes :terminal colors.
let g:terminal_color_0  = '${ISG_ANSI_0}'
let g:terminal_color_1  = '${ISG_ANSI_1}'
let g:terminal_color_2  = '${ISG_ANSI_2}'
let g:terminal_color_3  = '${ISG_ANSI_3}'
let g:terminal_color_4  = '${ISG_ANSI_4}'
let g:terminal_color_5  = '${ISG_ANSI_5}'
let g:terminal_color_6  = '${ISG_ANSI_6}'
let g:terminal_color_7  = '${ISG_ANSI_7}'
let g:terminal_color_8  = '${ISG_ANSI_8}'
let g:terminal_color_9  = '${ISG_ANSI_9}'
let g:terminal_color_10 = '${ISG_ANSI_10}'
let g:terminal_color_11 = '${ISG_ANSI_11}'
let g:terminal_color_12 = '${ISG_ANSI_12}'
let g:terminal_color_13 = '${ISG_ANSI_13}'
let g:terminal_color_14 = '${ISG_ANSI_14}'
let g:terminal_color_15 = '${ISG_ANSI_15}'

" =====================
" Basic UI colors
" =====================
hi Normal       guifg=${ISG_FG} guibg=${ISG_BG}
hi Cursor       guifg=${ISG_ON_ACCENT} guibg=${ISG_FG}
hi Visual       guibg=${ISG_VISUAL_BG}
hi LineNr       guifg=${ISG_GUTTER_FG} guibg=${ISG_BG}
hi CursorLineNr guifg=#999999 guibg=${ISG_BG}
hi StatusLine   guifg=${ISG_FG} guibg=${ISG_BG}
hi StatusLineNC guifg=${ISG_FG_FAINT} guibg=${ISG_BG}
hi VertSplit    guifg=${ISG_BORDER_UI} guibg=${ISG_BG_DEEP}
hi Pmenu        guifg=${ISG_FG} guibg=${ISG_BG_ALT}
hi PmenuSel     guifg=${ISG_ON_ACCENT} guibg=${ISG_BUTTON_BG}
hi Search       guifg=${ISG_FG} guibg=${ISG_SEARCH_BG}
hi IncSearch    guifg=${ISG_FG} guibg=${ISG_VISUAL_BG}

" =====================
" Comments
" =====================
hi Comment      guifg=${ISG_COMMENT} gui=italic

" =====================
" Constants / Numbers / Booleans
" =====================
hi Constant     guifg=${ISG_ACCENT}
hi Number       guifg=${ISG_NUMBER}
hi Boolean      guifg=${ISG_NUMBER}
hi String       guifg=${ISG_STRING}
hi Character    guifg=${ISG_STRING_ESCAPE}

" =====================
" Identifiers
" =====================
hi Identifier   guifg=${ISG_ACCENT}
hi Function     guifg=${ISG_ACCENT_DEEP}
hi Statement    guifg=${ISG_ACCENT}
hi Conditional  guifg=${ISG_ACCENT}
hi Repeat       guifg=${ISG_ACCENT}
hi Label        guifg=${ISG_ACCENT}
hi Operator     guifg=${ISG_FG}
hi Keyword      guifg=${ISG_ACCENT}
hi Exception    guifg=${ISG_ACCENT}
hi PreProc      guifg=${ISG_ACCENT}
hi Include      guifg=${ISG_ACCENT}
hi Define       guifg=${ISG_ACCENT}
hi Macro        guifg=${ISG_ACCENT}
hi Type         guifg=${ISG_ACCENT_DEEP}
hi StorageClass guifg=${ISG_ACCENT}
hi Structure    guifg=${ISG_ACCENT}
hi Typedef      guifg=${ISG_ACCENT_DEEP}
hi Special      guifg=${ISG_TAG}
hi SpecialChar  guifg=${ISG_STRING_ESCAPE}
hi Tag          guifg=${ISG_TAG}
hi Delimiter    guifg=${ISG_PUNCTUATION}
hi SpecialComment guifg=${ISG_DOC_COMMENT}
hi Debug        guifg=${ISG_ERROR}

" =====================
" Markdown / UI highlights
" =====================
hi Title        guifg=${ISG_TAG} gui=bold
hi Bold         guifg=${ISG_MD_BOLD} gui=bold
hi Italic       guifg=${ISG_ACCENT} gui=italic
hi Underlined   guifg=${ISG_ACCENT_DEEP} gui=underline
hi Todo         guifg=${ISG_STRING} guibg=NONE gui=bold

" =====================
" Diff / Git
" =====================
" Window-diff backgrounds (:diffthis, vimdiff)
hi DiffAdd      guifg=NONE    guibg=#E6FFEC
hi DiffChange   guifg=NONE    guibg=#E6FFEC
hi DiffDelete   guifg=NONE    guibg=#FFEBE9
hi DiffText     guifg=NONE    guibg=#ABF2BC gui=NONE

" Diff-as-text — reading a patch in a buffer (ft=diff/git, fugitive, :Git show).
" Explicit here too so a dark->light flip can't leave dark-background variants
" behind; gitsigns links its signs to Added/Removed/Changed.
" GitHub's diff palette, not ours — one use each, so no role.
hi Added        guifg=#1A7F37 guibg=NONE
hi Removed      guifg=#CF222E guibg=NONE
hi Changed      guifg=#9A6700 guibg=NONE
hi diffAdded    guifg=#1A7F37 guibg=NONE
hi diffRemoved  guifg=#CF222E guibg=NONE
hi diffChanged  guifg=#9A6700 guibg=NONE
hi diffFile     guifg=#0550AE guibg=NONE
hi diffIndexLine guifg=#57606A guibg=NONE
hi diffLine     guifg=#0969DA guibg=NONE
" `--- …` is usually a deleted `--` comment, not a file header — see vs_dark.vim
hi diffOldFile  guifg=#CF222E guibg=NONE
hi diffNewFile  guifg=#1A7F37 guibg=NONE

" =====================
" CursorLine and Search
" =====================
hi CursorLine   guibg=${ISG_LINE_HL}

" =====================
" Window filler / zen-mode backdrop
" =====================
hi EndOfBuffer  guifg=${ISG_BG} guibg=${ISG_BG}
hi WinSeparator guifg=${ISG_BG} guibg=${ISG_BG}
hi NonText      guifg=${ISG_BG} guibg=${ISG_BG}
hi ZenBg        guifg=${ISG_BG} guibg=${ISG_BG}
hi SignColumn   guibg=${ISG_BG}
hi FoldColumn   guibg=${ISG_BG}

" =====================
" nvim-tree highlights
" =====================
hi Directory             guifg=${ISG_ACCENT_DEEP}
hi NvimTreeFolderName    guifg=${ISG_ACCENT_DEEP}
hi NvimTreeOpenedFolderName guifg=${ISG_ACCENT_DEEP}
hi NvimTreeRootFolder    guifg=${ISG_TAG} gui=bold

" =====================
" Diagnostics (native neovim)
" =====================
hi DiagnosticError          guifg=${ISG_ERROR}
hi DiagnosticWarn           guifg=${ISG_DIAG_WARN}
hi DiagnosticInfo           guifg=${ISG_ACCENT_DEEP}
hi DiagnosticHint           guifg=${ISG_NUMBER}
hi DiagnosticUnderlineError gui=undercurl guisp=${ISG_ERROR}
hi DiagnosticUnderlineWarn  gui=undercurl guisp=${ISG_DIAG_WARN}
hi DiagnosticUnderlineInfo  gui=undercurl guisp=${ISG_ACCENT_DEEP}
hi DiagnosticUnderlineHint  gui=undercurl guisp=${ISG_NUMBER}

" =====================
" Enums (match VSCode Visual Studio Light)
" =====================
hi Enum                 guifg=${ISG_TYPE}
hi @type.enum           guifg=${ISG_TYPE}
hi @lsp.type.enum       guifg=${ISG_TYPE}
hi @lsp.type.enumMember guifg=${ISG_TYPE}
