" Dark (Visual Studio) color scheme for Neovim
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
" Separate from nvim-light.tpl: the two schemes declare different highlight
" groups, not just different colours.
"
" Colours with a single use are left as literal hex — naming a role with one
" consumer buys nothing. The substituted ones are the foundations that have to
" agree with the terminal, and the syntax roles shared with bat and k9s.

" 'background' first, then `hi clear`: hi clear recomputes Neovim's built-in
" defaults for the *current* background. Without it the light-background
" variants survive the theme flip — Added #005523, Removed #590008, ErrorMsg
" #590008, WarningMsg #6b5300, Question/MoreMsg #007373 — all near-black on
" this ${ISG_BG} background, which is why git diffs and gitsigns were unreadable.
set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'vs_dark'
set termguicolors

" Terminal/ANSI palette — the same 16 slots Ghostty publishes, from
" theme/palette.sh, so this can no longer drift from the terminal.
" baleia.nvim reads these g:terminal_color_* at setup() so captured-pane ANSI
" colors render identically to the live terminal instead of baleia's generic
" defaults. Also fixes :terminal colors.
let g:terminal_color_0  = '${ISG_ANSI_0}'
let g:terminal_color_1  = '${ISG_ANSI_1}'
let g:terminal_color_2  = '${ISG_ANSI_2}'
let g:terminal_color_3  = '${ISG_ANSI_3}'
let g:terminal_color_4  = '${ISG_ANSI_4}'
let g:terminal_color_5  = '${ISG_ANSI_5}'
let g:terminal_color_6  = '${ISG_ANSI_6}'
let g:terminal_color_7  = '${ISG_ANSI_7}'
let g:terminal_color_8  = '${ISG_ANSI_8}'
let g:terminal_color_9  = '${ISG_ANSI_9}'
let g:terminal_color_10 = '${ISG_ANSI_10}'
let g:terminal_color_11 = '${ISG_ANSI_11}'
let g:terminal_color_12 = '${ISG_ANSI_12}'
let g:terminal_color_13 = '${ISG_ANSI_13}'
let g:terminal_color_14 = '${ISG_ANSI_14}'
let g:terminal_color_15 = '${ISG_ANSI_15}'

" Editor colors
hi Normal       guifg=${ISG_FG} guibg=${ISG_BG}
hi CursorLine   guibg=${ISG_LINE_HL}
hi Visual       guibg=${ISG_VISUAL_BG}
hi LineNr       guifg=${ISG_GUTTER_FG} guibg=${ISG_BG}
hi CursorLineNr guifg=#888888 guibg=${ISG_BG}
hi StatusLine   guifg=${ISG_FG} guibg=${ISG_BG}
hi StatusLineNC guifg=${ISG_FG_FAINT} guibg=${ISG_BG}
hi VertSplit    guifg=${ISG_BORDER_UI} guibg=${ISG_BG_DEEP}
hi Pmenu        guifg=#CCCCCC guibg=${ISG_BG_ALT}
hi PmenuSel     guifg=${ISG_ON_ACCENT} guibg=${ISG_BUTTON_BG}
hi PmenuSbar    guibg=${ISG_BORDER_UI}
hi PmenuThumb   guibg=${ISG_BUTTON_FOCUS_BG}

" Comments
hi Comment      guifg=${ISG_COMMENT} gui=italic

" Constants
hi Constant     guifg=${ISG_ACCENT}
hi Number       guifg=${ISG_NUMBER}
hi Boolean      guifg=${ISG_ACCENT}
hi String       guifg=${ISG_STRING}
hi Character    guifg=${ISG_STRING}
hi Float        guifg=${ISG_NUMBER}
hi SpecialChar  guifg=${ISG_STRING_ESCAPE}

" Keywords
hi Keyword      guifg=${ISG_ACCENT}
hi Conditional  guifg=${ISG_ACCENT}
hi Repeat       guifg=${ISG_ACCENT}
hi Exception    guifg=${ISG_ACCENT}
hi Operator     guifg=${ISG_FG}
hi PreProc      guifg=${ISG_ACCENT}
hi Include      guifg=${ISG_ACCENT}
hi Define       guifg=${ISG_ACCENT}
hi Macro        guifg=${ISG_ACCENT}
hi Type         guifg=${ISG_ACCENT}
hi StorageClass guifg=${ISG_ACCENT}
hi Structure    guifg=${ISG_ACCENT}
hi Typedef      guifg=${ISG_ACCENT}

" Functions
hi Function     guifg=${ISG_FG}
hi Identifier   guifg=${ISG_ACCENT}
hi Method       guifg=${ISG_FG}
hi Statement    guifg=${ISG_ACCENT}

" Tags and markup
hi Tag          guifg=${ISG_TAG}
hi Label        guifg=${ISG_ACCENT}
hi Special      guifg=${ISG_ACCENT}
hi Delimiter    guifg=${ISG_PUNCTUATION}
hi Title        guifg=${ISG_ACCENT} gui=bold
hi Bold         gui=bold
hi Italic       gui=italic
hi Underlined   gui=underline
hi Error        guifg=${ISG_ERROR} guibg=${ISG_BG_DEEP} gui=bold
hi Todo         guifg=${ISG_NUMBER} guibg=NONE gui=bold

" Diff — window-diff backgrounds (:diffthis, vimdiff)
hi DiffAdd      guifg=NONE    guibg=#0D4429
hi DiffChange   guifg=NONE    guibg=#0D4429
hi DiffDelete   guifg=NONE    guibg=#3C1418
hi DiffText     guifg=NONE    guibg=#1A7F37 gui=NONE

" Diff-as-text — reading a patch in a buffer (ft=diff/git, fugitive, :Git show).
" Set explicitly rather than inherited: gitsigns links its signs to
" Added/Removed/Changed, so these three drive the gutter too.
" These are GitHub's diff palette, not ours — one use each, so no role.
hi Added        guifg=#3FB950 guibg=NONE
hi Removed      guifg=#F85149 guibg=NONE
hi Changed      guifg=#D29922 guibg=NONE
hi diffAdded    guifg=#3FB950 guibg=NONE
hi diffRemoved  guifg=#F85149 guibg=NONE
hi diffChanged  guifg=#D29922 guibg=NONE
hi diffFile     guifg=${ISG_ACCENT} guibg=NONE
hi diffIndexLine guifg=#808080 guibg=NONE
hi diffLine     guifg=${ISG_TAG_ATTR} guibg=NONE
" A deleted `--` comment (Lua, SQL) becomes `--- …`, which the diff syntax
" matches as the old-file header. Colour headers like the changes they sit on
" so those lines stop reading as blue metadata; `diff --git`/`index` still
" mark file boundaries.
hi diffOldFile  guifg=#F85149 guibg=NONE
hi diffNewFile  guifg=#3FB950 guibg=NONE

" Match parentheses
hi MatchParen   guibg=${ISG_SEARCH_BG}

" Search
hi Search       guifg=${ISG_FG} guibg=${ISG_SEARCH_BG}
hi IncSearch    guifg=${ISG_FG} guibg=${ISG_BUTTON_BG}

" Terminal colors
hi Terminal     guifg=${ISG_FG} guibg=${ISG_BG_DEEP}

" Popup and floating windows
hi FloatBorder  guifg=#303031
hi NormalFloat  guifg=${ISG_FG} guibg=${ISG_BG_DEEP}

" =====================
" Window filler / zen-mode backdrop
" =====================
hi EndOfBuffer  guifg=${ISG_BG} guibg=${ISG_BG}
hi WinSeparator guifg=${ISG_BG} guibg=${ISG_BG}
hi NonText      guifg=${ISG_BG} guibg=${ISG_BG}
hi ZenBg        guifg=${ISG_BG} guibg=${ISG_BG}
hi SignColumn   guibg=${ISG_BG}
hi FoldColumn   guibg=${ISG_BG}

" =====================
" nvim-tree highlights
" =====================
hi Directory                 guifg=${ISG_ACCENT_BRIGHT}
hi NvimTreeFolderName        guifg=${ISG_ACCENT} gui=bold
hi NvimTreeOpenedFolderName  guifg=${ISG_ACCENT} gui=bold
hi NvimTreeRootFolder        guifg=${ISG_ACCENT_BRIGHT} gui=bold

" =====================
" Diagnostics (replaces CoC highlights)
" =====================
hi DiagnosticError          guifg=${ISG_ERROR}
hi DiagnosticWarn           guifg=${ISG_DIAG_WARN}
hi DiagnosticInfo           guifg=${ISG_DIAG_WARN}
hi DiagnosticHint           guifg=${ISG_DIAG_WARN}
hi DiagnosticUnderlineError guibg=NONE gui=undercurl guisp=${ISG_ERROR}
hi DiagnosticUnderlineWarn  guibg=NONE gui=undercurl guisp=${ISG_DIAG_WARN}
hi DiagnosticUnderlineInfo  guibg=NONE gui=undercurl guisp=${ISG_DIAG_WARN}
hi DiagnosticUnderlineHint  guibg=NONE gui=undercurl guisp=${ISG_DIAG_WARN}
hi DiagnosticUnnecessary    guifg=${ISG_FG_FAINT} gui=undercurl guisp=${ISG_FG_FAINT}
hi DiagnosticDeprecated     gui=strikethrough guisp=${ISG_FG_FAINT}

" =====================
" Treesitter highlights
" =====================
hi @variable            guifg=${ISG_FG}
hi @variable.parameter  guifg=${ISG_FG}
hi @variable.member     guifg=${ISG_FG}
hi @variable.builtin    guifg=${ISG_ACCENT}

" Enums (match VSCode Visual Studio Dark)
hi Enum                 guifg=${ISG_TYPE}
hi @type.enum           guifg=${ISG_TYPE}
hi @lsp.type.enum       guifg=${ISG_TYPE}
hi @lsp.type.enumMember guifg=${ISG_TYPE}
