# tmux ${ISG_MODE} theme — GENERATED by theme/generate.sh.
# Edit theme/palette.sh, not this file.
#
# Sourced by .tmux.conf, which reads ~/.config/isg/theme at parse time (see the
# run-shell block there). Re-source ~/.tmux.conf to repaint; toggle_theme.sh
# does that for you, which is why tmux is the one tool that flips live.
#
# Every style keeps bg=default so the terminal background shows through and the
# status line reads as part of the pane instead of a band painted over it. Don't
# give these a background — it is what keeps the layout seamless.
set -g status-style "bg=default,fg=${ISG_UI_FG}"
set -g status-left "[#S]#{?#{||:#{==:#{client_key_table},plugins},#{==:#{client_key_table},splits}},#[fg=${ISG_UI_FG_STRONG}#,bold]+#[default] ,#{?client_prefix,#[fg=${ISG_UI_FG_STRONG}#,bold]*#[default] ,  }}"
set -g window-status-style "bg=default,fg=${ISG_UI_FG_DIM}"
set -g window-status-current-style "bg=default,fg=${ISG_UI_FG_STRONG},bold"
# Alert flag (monitor-silence / -activity / -bell). tmux defaults this to
# `reverse`, which on a bg=default bar paints a filled block and reads as a
# rendering fault. Underscore instead: the palette here is greyscale, bold is
# already spoken for by the current window, and an underline is the one
# attribute left that draws the eye without inventing a colour.
set -g window-status-activity-style "bg=default,fg=${ISG_UI_FG_STRONG},underscore"
set -g status-left-style "bg=default,fg=${ISG_UI_FG}"
set -g status-right-style "bg=default,fg=${ISG_UI_FG}"
set -g message-style "bg=default,fg=${ISG_UI_MSG}"
set -g pane-border-style "fg=${ISG_BORDER}"
set -g pane-active-border-style "fg=${ISG_BORDER_ACTIVE}"
