# tmux ${ISG_MODE} theme — GENERATED by theme/generate.sh.
# Edit theme/palette.sh, not this file.
#
# Sourced by .tmux.conf, which reads ~/.config/isg/theme at parse time (see the
# run-shell block there). Re-source ~/.tmux.conf to repaint; toggle_theme.sh
# does that for you, which is why tmux is the one tool that flips live.
#
# Every style keeps bg=default so the terminal background shows through and the
# status line reads as part of the pane instead of a band painted over it. Don't
# give these a background — it is what keeps the layout seamless.
set -g status-style "bg=default,fg=${ISG_UI_FG}"
set -g status-left "[#S]#{?client_prefix,#[fg=${ISG_UI_FG_STRONG}#,bold]*#[default] ,  }"
set -g window-status-style "bg=default,fg=${ISG_UI_FG_DIM}"
set -g window-status-current-style "bg=default,fg=${ISG_UI_FG_STRONG},bold"
set -g status-left-style "bg=default,fg=${ISG_UI_FG}"
set -g status-right-style "bg=default,fg=${ISG_UI_FG}"
set -g message-style "bg=default,fg=${ISG_UI_MSG}"
set -g pane-border-style "fg=${ISG_BORDER}"
set -g pane-active-border-style "fg=${ISG_BORDER_ACTIVE}"
