" Filename: dark_vscode.vim
" Description: VSCode Dark theme ported to Vim with termguicolors
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
"
" Kept separate from nvim-dark.tpl on purpose. Vim 9 accepts every construct the
" Neovim scheme uses, so one file *could* serve both — but the two have diverged
" where it shows: this statusline is a filled colour bar and its diffs tint the
" foreground, while Neovim's statusline is seamless and its diffs colour the
" background. Unifying them would change what vim looks like, so for now vim
" simply follows the same palette. It also targets CoC and NERDTree rather than
" native LSP and nvim-tree.
"
" Colours with a single use stay literal hex.

if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'vs_dark'
set background=dark
set termguicolors

" Editor colors
hi Normal       guifg=${ISG_FG} guibg=${ISG_BG}
hi CursorLine   guibg=${ISG_LINE_HL}
hi Visual       guibg=${ISG_VISUAL_BG}
hi LineNr       guifg=${ISG_GUTTER_FG} guibg=${ISG_BG}
hi CursorLineNr guifg=#888888 guibg=${ISG_BG}
hi StatusLine   guifg=${ISG_FG} guibg=${ISG_VIM_STATUS_BG}
hi StatusLineNC guifg=${ISG_VIM_STATUS_NC_FG} guibg=${ISG_BG_DEEP}
hi VertSplit    guifg=${ISG_BORDER_UI} guibg=${ISG_BG_DEEP}
hi Pmenu        guifg=#CCCCCC guibg=${ISG_BG_ALT}
hi PmenuSel     guifg=${ISG_ON_ACCENT} guibg=${ISG_BUTTON_BG}
hi PmenuSbar    guibg=${ISG_BORDER_UI}
hi PmenuThumb   guibg=${ISG_BUTTON_FOCUS_BG}

" Comments
hi Comment      guifg=${ISG_COMMENT} gui=italic

" Constants
hi Constant     guifg=${ISG_ACCENT}
hi Number       guifg=${ISG_NUMBER}
hi Boolean      guifg=${ISG_ACCENT}
hi String       guifg=${ISG_STRING}
hi Character    guifg=${ISG_STRING}
hi Float        guifg=${ISG_NUMBER}
hi SpecialChar  guifg=${ISG_STRING_ESCAPE}

" Keywords
hi Keyword      guifg=${ISG_ACCENT}
hi Conditional  guifg=${ISG_ACCENT}
hi Repeat       guifg=${ISG_ACCENT}
hi Exception    guifg=${ISG_ACCENT}
hi Operator     guifg=${ISG_FG}
hi PreProc      guifg=${ISG_ACCENT}
hi Include      guifg=${ISG_ACCENT}
hi Define       guifg=${ISG_ACCENT}
hi Macro        guifg=${ISG_ACCENT}
hi Type         guifg=${ISG_ACCENT}
hi StorageClass guifg=${ISG_ACCENT}
hi Structure    guifg=${ISG_ACCENT}
hi Typedef      guifg=${ISG_ACCENT}

" Functions
hi Function     guifg=${ISG_FG}
hi Identifier   guifg=${ISG_ACCENT}
hi Method       guifg=${ISG_FG}
hi Statement    guifg=${ISG_ACCENT}

" Tags and markup
hi Tag          guifg=${ISG_TAG}
hi Label        guifg=${ISG_ACCENT}
hi Special      guifg=${ISG_ACCENT}
hi Delimiter    guifg=${ISG_PUNCTUATION}
hi Title        guifg=${ISG_ACCENT} gui=bold
hi Bold         gui=bold
hi Italic       gui=italic
hi Underlined   gui=underline
hi Error        guifg=${ISG_ERROR} guibg=${ISG_BG_DEEP} gui=bold
hi Todo         guifg=${ISG_NUMBER} guibg=NONE gui=bold

" Diff — foreground-tinted, unlike Neovim's background-based diffs
hi DiffAdd      guifg=${ISG_NUMBER} guibg=${ISG_BG_DEEP}
hi DiffChange   guifg=${ISG_ACCENT} guibg=${ISG_BG_DEEP}
hi DiffDelete   guifg=${ISG_STRING} guibg=${ISG_BG_DEEP}
hi DiffText     guifg=${ISG_ACCENT} guibg=${ISG_BG_DEEP}

" Match parentheses
hi MatchParen   guibg=${ISG_SEARCH_BG}

" Search
hi Search       guifg=${ISG_FG} guibg=${ISG_SEARCH_BG}
hi IncSearch    guifg=${ISG_FG} guibg=${ISG_BUTTON_BG}

" Terminal colors
hi Terminal     guifg=${ISG_FG} guibg=${ISG_BG_DEEP}

" Popup and floating windows
hi FloatBorder  guifg=#303031
hi NormalFloat  guifg=${ISG_FG} guibg=${ISG_BG_DEEP}

" Set folder color (optional)
hi NERDTreeDir guifg=${ISG_ACCENT} gui=bold

" Directory and NERDTree arrows/bullets (lighter blue for readability)
hi Directory          guifg=${ISG_ACCENT_BRIGHT}
hi NERDTreeOpenable   guifg=${ISG_ACCENT_BRIGHT}
hi NERDTreeClosable   guifg=${ISG_ACCENT_BRIGHT}
hi NERDTreeDirSlash   guifg=${ISG_ACCENT_BRIGHT}
hi NERDTreeUp         guifg=${ISG_ACCENT_BRIGHT}

" CoC error/warning highlights (colored text, no background)
hi CocErrorHighlight   guibg=NONE guifg=${ISG_ERROR} gui=undercurl guisp=${ISG_ERROR} cterm=underline ctermfg=Red
hi CocWarningHighlight guibg=NONE guifg=${ISG_DIAG_WARN} gui=undercurl guisp=${ISG_DIAG_WARN} cterm=underline ctermfg=Yellow
hi CocInfoHighlight    guibg=NONE guifg=${ISG_DIAG_WARN} gui=undercurl guisp=${ISG_DIAG_WARN} cterm=underline ctermfg=Yellow
hi CocHintHighlight    guibg=NONE guifg=${ISG_DIAG_WARN} gui=undercurl guisp=${ISG_DIAG_WARN} cterm=underline ctermfg=Yellow
hi CocUnusedHighlight  guibg=NONE guifg=${ISG_FG_FAINT} gui=undercurl guisp=${ISG_FG_FAINT} cterm=underline ctermfg=Grey
hi CocDeprecatedHighlight guibg=NONE gui=strikethrough guisp=${ISG_FG_FAINT} cterm=strikethrough
hi CocErrorLine        guibg=NONE
hi CocWarningLine      guibg=NONE

" Enums (match VSCode Visual Studio Dark)
hi Enum             guifg=${ISG_TYPE}
hi CocSemEnum       guifg=${ISG_TYPE}
hi CocSemEnumMember guifg=${ISG_TYPE}
