" Light (Visual Studio) Vim color scheme
" Author: Converted from VS Code theme
" Usage: place this file in ~/.vim/colors/ and use :colorscheme light
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
"
" Kept separate from nvim-light.tpl — see the note in vim-dark.tpl. Vim's
" statusline is a filled bar (green here, blue on dark: they never matched each
" other either) and its diffs tint the foreground over a pale wash, where Neovim
" colours the background.
"
" The duplicate Search and Visual lines below are in the original and are kept:
" harmless, and removing them is a change to a generated file's behaviour, not a
" palette question.

if exists("syntax_on")
  syntax reset
endif

set background=light
let g:colors_name = "vs_light"

" Terminal cursor colour. Unlike Neovim — which emits OSC 12 for whatever group
" 'guicursor' names — terminal Vim never turns `hi Cursor` into an escape, so
" the group below only reaches a GUI. Publish the hex as well and let .vimrc
" write OSC 12 itself; that is what keeps the caret in step with a theme toggle
" while the running Ghostty still holds the old cursor-color.
let g:isg_cursor = '${ISG_CURSOR}'

" =====================
" Basic UI colors
" =====================
hi Normal       guifg=${ISG_FG} guibg=${ISG_BG}
hi Cursor       guifg=${ISG_BG} guibg=${ISG_CURSOR}
hi Visual       guibg=${ISG_VISUAL_BG}
hi LineNr       guifg=${ISG_GUTTER_FG} guibg=${ISG_BG}
hi CursorLineNr guifg=#999999 guibg=${ISG_BG}
hi StatusLine   guifg=${ISG_ON_ACCENT} guibg=${ISG_VIM_STATUS_BG}
hi StatusLineNC guifg=${ISG_VIM_STATUS_NC_FG} guibg=${ISG_BG_ALT}
hi VertSplit    guifg=${ISG_BORDER_UI} guibg=${ISG_BG_DEEP}
hi Pmenu        guifg=${ISG_FG} guibg=${ISG_BG_ALT}
hi PmenuSel     guifg=${ISG_ON_ACCENT} guibg=${ISG_BUTTON_BG}
hi Search       guifg=${ISG_FG} guibg=${ISG_SEARCH_BG}
hi IncSearch    guifg=${ISG_FG} guibg=${ISG_VISUAL_BG}

" =====================
" Comments
" =====================
hi Comment      guifg=${ISG_COMMENT} gui=italic

" =====================
" Constants / Numbers / Booleans
" =====================
hi Constant     guifg=${ISG_ACCENT}
hi Number       guifg=${ISG_NUMBER}
hi Boolean      guifg=${ISG_NUMBER}
hi String       guifg=${ISG_STRING}
hi Character    guifg=${ISG_STRING_ESCAPE}

" =====================
" Identifiers
" =====================
hi Identifier   guifg=${ISG_ACCENT}
hi Function     guifg=${ISG_ACCENT_DEEP}
hi Statement    guifg=${ISG_ACCENT}
hi Conditional  guifg=${ISG_ACCENT}
hi Repeat       guifg=${ISG_ACCENT}
hi Label        guifg=${ISG_ACCENT}
hi Operator     guifg=${ISG_FG}
hi Keyword      guifg=${ISG_ACCENT}
hi Exception    guifg=${ISG_ACCENT}
hi PreProc      guifg=${ISG_ACCENT}
hi Include      guifg=${ISG_ACCENT}
hi Define       guifg=${ISG_ACCENT}
hi Macro        guifg=${ISG_ACCENT}
hi Type         guifg=${ISG_ACCENT_DEEP}
hi StorageClass guifg=${ISG_ACCENT}
hi Structure    guifg=${ISG_ACCENT}
hi Typedef      guifg=${ISG_ACCENT_DEEP}
hi Special      guifg=${ISG_TAG}
hi SpecialChar  guifg=${ISG_STRING_ESCAPE}
hi Tag          guifg=${ISG_TAG}
hi Delimiter    guifg=${ISG_PUNCTUATION}
hi SpecialComment guifg=${ISG_DOC_COMMENT}
hi Debug        guifg=${ISG_ERROR}

" =====================
" Markdown / UI highlights
" =====================
hi Title        guifg=${ISG_TAG} gui=bold
hi Bold         guifg=${ISG_MD_BOLD} gui=bold
hi Italic       guifg=${ISG_ACCENT} gui=italic
hi Underlined   guifg=${ISG_ACCENT_DEEP} gui=underline
hi Todo         guifg=${ISG_STRING} guibg=NONE gui=bold

" =====================
" Diff / Git
" =====================
" Foreground-tinted over a pale wash, unlike Neovim's background-based diffs.
" The four washes are used once each, so they stay literal.
hi DiffAdd      guifg=${ISG_NUMBER} guibg=#E8F8F5
hi DiffChange   guifg=${ISG_ACCENT_DEEP} guibg=#F0F0FF
hi DiffDelete   guifg=${ISG_STRING} guibg=#FFECEC
hi DiffText     guifg=${ISG_FG} guibg=#FFD700

" =====================
" CursorLine and Search
" =====================
hi CursorLine   guibg=${ISG_LINE_HL}
hi Search       guibg=${ISG_SEARCH_BG} guifg=${ISG_FG}
hi Visual       guibg=${ISG_VISUAL_BG}

" =====================
" Enums (match VSCode Visual Studio Light)
" =====================
hi Enum             guifg=${ISG_TYPE}
hi CocSemEnum       guifg=${ISG_TYPE}
hi CocSemEnumMember guifg=${ISG_TYPE}

" =====================
" End
" =====================
