" Dark (Visual Studio) color scheme for Neovim
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
" Separate from nvim-light.tpl: the two schemes declare different highlight
" groups, not just different colours.
"
" Colours with a single use are left as literal hex — naming a role with one
" consumer buys nothing. The substituted ones are the foundations that have to
" agree with the terminal, and the syntax roles shared with bat and k9s.

" 'background' first, then `hi clear`: hi clear recomputes Neovim's built-in
" defaults for the *current* background. Without it the light-background
" variants survive the theme flip — Added #005523, Removed #590008, ErrorMsg
" #590008, WarningMsg #6b5300, Question/MoreMsg #007373 — all near-black on
" this #2f2f2f background, which is why git diffs and gitsigns were unreadable.
set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'vs_dark'
set termguicolors

" Terminal/ANSI palette — the same 16 slots Ghostty publishes, from
" theme/palette.sh, so this can no longer drift from the terminal.
" baleia.nvim reads these g:terminal_color_* at setup() so captured-pane ANSI
" colors render identically to the live terminal instead of baleia's generic
" defaults. Also fixes :terminal colors.
let g:terminal_color_0  = '#45475a'
let g:terminal_color_1  = '#f38ba8'
let g:terminal_color_2  = '#a6e3a1'
let g:terminal_color_3  = '#f9e2af'
let g:terminal_color_4  = '#89b4fa'
let g:terminal_color_5  = '#f5c2e7'
let g:terminal_color_6  = '#94e2d5'
let g:terminal_color_7  = '#a6adc8'
let g:terminal_color_8  = '#585b70'
let g:terminal_color_9  = '#f37799'
let g:terminal_color_10 = '#89d88b'
let g:terminal_color_11 = '#ebd391'
let g:terminal_color_12 = '#74a8fc'
let g:terminal_color_13 = '#f2aede'
let g:terminal_color_14 = '#6bd7ca'
let g:terminal_color_15 = '#bac2de'

" Editor colors
hi Normal       guifg=#d4d4d4 guibg=#2f2f2f
hi CursorLine   guibg=#2a2a2a
hi Visual       guibg=#3a3d41
hi LineNr       guifg=#555555 guibg=#2f2f2f
hi CursorLineNr guifg=#888888 guibg=#2f2f2f
hi StatusLine   guifg=#d4d4d4 guibg=#2f2f2f
hi StatusLineNC guifg=#6b6b6b guibg=#2f2f2f
hi VertSplit    guifg=#454545 guibg=#1e1e1e
hi Pmenu        guifg=#CCCCCC guibg=#252526
hi PmenuSel     guifg=#ffffff guibg=#0078d4
hi PmenuSbar    guibg=#454545
hi PmenuThumb   guibg=#007acc

" Comments
hi Comment      guifg=#888888 gui=italic

" Constants
hi Constant     guifg=#569cd6
hi Number       guifg=#b5cea8
hi Boolean      guifg=#569cd6
hi String       guifg=#ce9178
hi Character    guifg=#ce9178
hi Float        guifg=#b5cea8
hi SpecialChar  guifg=#d16969

" Keywords
hi Keyword      guifg=#569cd6
hi Conditional  guifg=#569cd6
hi Repeat       guifg=#569cd6
hi Exception    guifg=#569cd6
hi Operator     guifg=#d4d4d4
hi PreProc      guifg=#569cd6
hi Include      guifg=#569cd6
hi Define       guifg=#569cd6
hi Macro        guifg=#569cd6
hi Type         guifg=#569cd6
hi StorageClass guifg=#569cd6
hi Structure    guifg=#569cd6
hi Typedef      guifg=#569cd6

" Functions
hi Function     guifg=#d4d4d4
hi Identifier   guifg=#569cd6
hi Method       guifg=#d4d4d4
hi Statement    guifg=#569cd6

" Tags and markup
hi Tag          guifg=#569cd6
hi Label        guifg=#569cd6
hi Special      guifg=#569cd6
hi Delimiter    guifg=#888888
hi Title        guifg=#569cd6 gui=bold
hi Bold         gui=bold
hi Italic       gui=italic
hi Underlined   gui=underline
hi Error        guifg=#f44747 guibg=#1e1e1e gui=bold
hi Todo         guifg=#b5cea8 guibg=NONE gui=bold

" Diff — window-diff backgrounds (:diffthis, vimdiff)
hi DiffAdd      guifg=NONE    guibg=#0D4429
hi DiffChange   guifg=NONE    guibg=#0D4429
hi DiffDelete   guifg=NONE    guibg=#3C1418
hi DiffText     guifg=NONE    guibg=#1A7F37 gui=NONE

" Diff-as-text — reading a patch in a buffer (ft=diff/git, fugitive, :Git show).
" Set explicitly rather than inherited: gitsigns links its signs to
" Added/Removed/Changed, so these three drive the gutter too.
" These are GitHub's diff palette, not ours — one use each, so no role.
hi Added        guifg=#3FB950 guibg=NONE
hi Removed      guifg=#F85149 guibg=NONE
hi Changed      guifg=#D29922 guibg=NONE
hi diffAdded    guifg=#3FB950 guibg=NONE
hi diffRemoved  guifg=#F85149 guibg=NONE
hi diffChanged  guifg=#D29922 guibg=NONE
hi diffFile     guifg=#569cd6 guibg=NONE
hi diffIndexLine guifg=#808080 guibg=NONE
hi diffLine     guifg=#9cdcfe guibg=NONE
" A deleted `--` comment (Lua, SQL) becomes `--- …`, which the diff syntax
" matches as the old-file header. Colour headers like the changes they sit on
" so those lines stop reading as blue metadata; `diff --git`/`index` still
" mark file boundaries.
hi diffOldFile  guifg=#F85149 guibg=NONE
hi diffNewFile  guifg=#3FB950 guibg=NONE

" Match parentheses
hi MatchParen   guibg=#264f78

" Search
hi Search       guifg=#d4d4d4 guibg=#264f78
hi IncSearch    guifg=#d4d4d4 guibg=#0078d4

" Terminal colors
hi Terminal     guifg=#d4d4d4 guibg=#1e1e1e

" Popup and floating windows
hi FloatBorder  guifg=#303031
hi NormalFloat  guifg=#d4d4d4 guibg=#1e1e1e

" =====================
" Window filler / zen-mode backdrop
" =====================
hi EndOfBuffer  guifg=#2f2f2f guibg=#2f2f2f
hi WinSeparator guifg=#2f2f2f guibg=#2f2f2f
hi NonText      guifg=#2f2f2f guibg=#2f2f2f
hi ZenBg        guifg=#2f2f2f guibg=#2f2f2f
hi SignColumn   guibg=#2f2f2f
hi FoldColumn   guibg=#2f2f2f

" =====================
" nvim-tree highlights
" =====================
hi Directory                 guifg=#87cfff
hi NvimTreeFolderName        guifg=#569cd6 gui=bold
hi NvimTreeOpenedFolderName  guifg=#569cd6 gui=bold
hi NvimTreeRootFolder        guifg=#87cfff gui=bold

" =====================
" Diagnostics (replaces CoC highlights)
" =====================
hi DiagnosticError          guifg=#f44747
hi DiagnosticWarn           guifg=#cca700
hi DiagnosticInfo           guifg=#cca700
hi DiagnosticHint           guifg=#cca700
hi DiagnosticUnderlineError guibg=NONE gui=undercurl guisp=#f44747
hi DiagnosticUnderlineWarn  guibg=NONE gui=undercurl guisp=#cca700
hi DiagnosticUnderlineInfo  guibg=NONE gui=undercurl guisp=#cca700
hi DiagnosticUnderlineHint  guibg=NONE gui=undercurl guisp=#cca700
hi DiagnosticUnnecessary    guifg=#6b6b6b gui=undercurl guisp=#6b6b6b
hi DiagnosticDeprecated     gui=strikethrough guisp=#6b6b6b

" =====================
" Treesitter highlights
" =====================
hi @variable            guifg=#d4d4d4
hi @variable.parameter  guifg=#d4d4d4
hi @variable.member     guifg=#d4d4d4
hi @variable.builtin    guifg=#569cd6

" Enums (match VSCode Visual Studio Dark)
hi Enum                 guifg=#4ec9b0
hi @type.enum           guifg=#4ec9b0
hi @lsp.type.enum       guifg=#4ec9b0
hi @lsp.type.enumMember guifg=#4ec9b0
