" Light (Visual Studio) color scheme for Neovim
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
" Separate from nvim-dark.tpl: this scheme colours Bold/Italic/Underlined and
" declares SpecialComment and Debug, while leaving out MatchParen, Terminal,
" NormalFloat and the treesitter @variable groups. Different files, not just
" different colours.
"
" Colours with a single use stay literal hex — naming a role with one consumer
" buys nothing.

" 'background' first, then `hi clear` — see the same note in vs_dark.vim. Light
" happens to be the background Neovim's defaults were already computed for, but
" relying on that breaks as soon as the theme is flipped the other way.
set background=light
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "vs_light"

" Terminal/ANSI palette — the same 16 slots Ghostty publishes, from
" theme/palette.sh, so this can no longer drift from the terminal.
" baleia.nvim reads these g:terminal_color_* at setup() so captured-pane ANSI
" colors render identically to the live terminal instead of baleia's generic
" defaults. Also fixes :terminal colors.
let g:terminal_color_0  = '#5c5f77'
let g:terminal_color_1  = '#d20f39'
let g:terminal_color_2  = '#40a02b'
let g:terminal_color_3  = '#df8e1d'
let g:terminal_color_4  = '#1e66f5'
let g:terminal_color_5  = '#ea76cb'
let g:terminal_color_6  = '#179299'
let g:terminal_color_7  = '#acb0be'
let g:terminal_color_8  = '#6c6f85'
let g:terminal_color_9  = '#de293e'
let g:terminal_color_10 = '#49af3d'
let g:terminal_color_11 = '#eea02d'
let g:terminal_color_12 = '#456eff'
let g:terminal_color_13 = '#fe85d8'
let g:terminal_color_14 = '#2d9fa8'
let g:terminal_color_15 = '#bcc0cc'

" =====================
" Basic UI colors
" =====================
hi Normal       guifg=#000000 guibg=#fafafa
hi Cursor       guifg=#ffffff guibg=#000000
hi Visual       guibg=#add6ff
hi LineNr       guifg=#c0c0c0 guibg=#fafafa
hi CursorLineNr guifg=#999999 guibg=#fafafa
hi StatusLine   guifg=#000000 guibg=#fafafa
hi StatusLineNC guifg=#aaaaaa guibg=#fafafa
hi VertSplit    guifg=#d4d4d4 guibg=#ffffff
hi Pmenu        guifg=#000000 guibg=#f3f3f3
hi PmenuSel     guifg=#ffffff guibg=#007acc
hi Search       guifg=#000000 guibg=#90c2f9
hi IncSearch    guifg=#000000 guibg=#add6ff

" =====================
" Comments
" =====================
hi Comment      guifg=#999999 gui=italic

" =====================
" Constants / Numbers / Booleans
" =====================
hi Constant     guifg=#0000ff
hi Number       guifg=#098658
hi Boolean      guifg=#098658
hi String       guifg=#a31515
hi Character    guifg=#811f3f

" =====================
" Identifiers
" =====================
hi Identifier   guifg=#0000ff
hi Function     guifg=#0451a5
hi Statement    guifg=#0000ff
hi Conditional  guifg=#0000ff
hi Repeat       guifg=#0000ff
hi Label        guifg=#0000ff
hi Operator     guifg=#000000
hi Keyword      guifg=#0000ff
hi Exception    guifg=#0000ff
hi PreProc      guifg=#0000ff
hi Include      guifg=#0000ff
hi Define       guifg=#0000ff
hi Macro        guifg=#0000ff
hi Type         guifg=#0451a5
hi StorageClass guifg=#0000ff
hi Structure    guifg=#0000ff
hi Typedef      guifg=#0451a5
hi Special      guifg=#800000
hi SpecialChar  guifg=#811f3f
hi Tag          guifg=#800000
hi Delimiter    guifg=#000000
hi SpecialComment guifg=#008000
hi Debug        guifg=#ff0000

" =====================
" Markdown / UI highlights
" =====================
hi Title        guifg=#800000 gui=bold
hi Bold         guifg=#000080 gui=bold
hi Italic       guifg=#0000ff gui=italic
hi Underlined   guifg=#0451a5 gui=underline
hi Todo         guifg=#a31515 guibg=NONE gui=bold

" =====================
" Diff / Git
" =====================
" Window-diff backgrounds (:diffthis, vimdiff)
hi DiffAdd      guifg=NONE    guibg=#E6FFEC
hi DiffChange   guifg=NONE    guibg=#E6FFEC
hi DiffDelete   guifg=NONE    guibg=#FFEBE9
hi DiffText     guifg=NONE    guibg=#ABF2BC gui=NONE

" Diff-as-text — reading a patch in a buffer (ft=diff/git, fugitive, :Git show).
" Explicit here too so a dark->light flip can't leave dark-background variants
" behind; gitsigns links its signs to Added/Removed/Changed.
" GitHub's diff palette, not ours — one use each, so no role.
hi Added        guifg=#1A7F37 guibg=NONE
hi Removed      guifg=#CF222E guibg=NONE
hi Changed      guifg=#9A6700 guibg=NONE
hi diffAdded    guifg=#1A7F37 guibg=NONE
hi diffRemoved  guifg=#CF222E guibg=NONE
hi diffChanged  guifg=#9A6700 guibg=NONE
hi diffFile     guifg=#0550AE guibg=NONE
hi diffIndexLine guifg=#57606A guibg=NONE
hi diffLine     guifg=#0969DA guibg=NONE
" `--- …` is usually a deleted `--` comment, not a file header — see vs_dark.vim
hi diffOldFile  guifg=#CF222E guibg=NONE
hi diffNewFile  guifg=#1A7F37 guibg=NONE

" =====================
" CursorLine and Search
" =====================
hi CursorLine   guibg=#e5ebf1

" =====================
" Window filler / zen-mode backdrop
" =====================
hi EndOfBuffer  guifg=#fafafa guibg=#fafafa
hi WinSeparator guifg=#fafafa guibg=#fafafa
hi NonText      guifg=#fafafa guibg=#fafafa
hi ZenBg        guifg=#fafafa guibg=#fafafa
hi SignColumn   guibg=#fafafa
hi FoldColumn   guibg=#fafafa

" =====================
" nvim-tree highlights
" =====================
hi Directory             guifg=#0451a5
hi NvimTreeFolderName    guifg=#0451a5
hi NvimTreeOpenedFolderName guifg=#0451a5
hi NvimTreeRootFolder    guifg=#800000 gui=bold

" =====================
" Diagnostics (native neovim)
" =====================
hi DiagnosticError          guifg=#ff0000
hi DiagnosticWarn           guifg=#bf8803
hi DiagnosticInfo           guifg=#0451a5
hi DiagnosticHint           guifg=#098658
hi DiagnosticUnderlineError gui=undercurl guisp=#ff0000
hi DiagnosticUnderlineWarn  gui=undercurl guisp=#bf8803
hi DiagnosticUnderlineInfo  gui=undercurl guisp=#0451a5
hi DiagnosticUnderlineHint  gui=undercurl guisp=#098658

" =====================
" Enums (match VSCode Visual Studio Light)
" =====================
hi Enum                 guifg=#267f99
hi @type.enum           guifg=#267f99
hi @lsp.type.enum       guifg=#267f99
hi @lsp.type.enumMember guifg=#267f99
