" Filename: dark_vscode.vim
" Description: VSCode Dark theme ported to Vim with termguicolors
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
"
" Kept separate from nvim-dark.tpl on purpose. Vim 9 accepts every construct the
" Neovim scheme uses, so one file *could* serve both — but the two have diverged
" where it shows: this statusline is a filled colour bar and its diffs tint the
" foreground, while Neovim's statusline is seamless and its diffs colour the
" background. Unifying them would change what vim looks like, so for now vim
" simply follows the same palette. It also targets CoC and NERDTree rather than
" native LSP and nvim-tree.
"
" Colours with a single use stay literal hex.

if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'vs_dark'
set background=dark
set termguicolors

" Editor colors
hi Normal       guifg=#d4d4d4 guibg=#2f2f2f
hi CursorLine   guibg=#2a2a2a
hi Visual       guibg=#3a3d41
hi LineNr       guifg=#555555 guibg=#2f2f2f
hi CursorLineNr guifg=#888888 guibg=#2f2f2f
hi StatusLine   guifg=#d4d4d4 guibg=#007acc
hi StatusLineNC guifg=#bbbbbb guibg=#1e1e1e
hi VertSplit    guifg=#454545 guibg=#1e1e1e
hi Pmenu        guifg=#CCCCCC guibg=#252526
hi PmenuSel     guifg=#ffffff guibg=#0078d4
hi PmenuSbar    guibg=#454545
hi PmenuThumb   guibg=#007acc

" Comments
hi Comment      guifg=#888888 gui=italic

" Constants
hi Constant     guifg=#569cd6
hi Number       guifg=#b5cea8
hi Boolean      guifg=#569cd6
hi String       guifg=#ce9178
hi Character    guifg=#ce9178
hi Float        guifg=#b5cea8
hi SpecialChar  guifg=#d16969

" Keywords
hi Keyword      guifg=#569cd6
hi Conditional  guifg=#569cd6
hi Repeat       guifg=#569cd6
hi Exception    guifg=#569cd6
hi Operator     guifg=#d4d4d4
hi PreProc      guifg=#569cd6
hi Include      guifg=#569cd6
hi Define       guifg=#569cd6
hi Macro        guifg=#569cd6
hi Type         guifg=#569cd6
hi StorageClass guifg=#569cd6
hi Structure    guifg=#569cd6
hi Typedef      guifg=#569cd6

" Functions
hi Function     guifg=#d4d4d4
hi Identifier   guifg=#569cd6
hi Method       guifg=#d4d4d4
hi Statement    guifg=#569cd6

" Tags and markup
hi Tag          guifg=#569cd6
hi Label        guifg=#569cd6
hi Special      guifg=#569cd6
hi Delimiter    guifg=#888888
hi Title        guifg=#569cd6 gui=bold
hi Bold         gui=bold
hi Italic       gui=italic
hi Underlined   gui=underline
hi Error        guifg=#f44747 guibg=#1e1e1e gui=bold
hi Todo         guifg=#b5cea8 guibg=NONE gui=bold

" Diff — foreground-tinted, unlike Neovim's background-based diffs
hi DiffAdd      guifg=#b5cea8 guibg=#1e1e1e
hi DiffChange   guifg=#569cd6 guibg=#1e1e1e
hi DiffDelete   guifg=#ce9178 guibg=#1e1e1e
hi DiffText     guifg=#569cd6 guibg=#1e1e1e

" Match parentheses
hi MatchParen   guibg=#264f78

" Search
hi Search       guifg=#d4d4d4 guibg=#264f78
hi IncSearch    guifg=#d4d4d4 guibg=#0078d4

" Terminal colors
hi Terminal     guifg=#d4d4d4 guibg=#1e1e1e

" Popup and floating windows
hi FloatBorder  guifg=#303031
hi NormalFloat  guifg=#d4d4d4 guibg=#1e1e1e

" Set folder color (optional)
hi NERDTreeDir guifg=#569cd6 gui=bold

" Directory and NERDTree arrows/bullets (lighter blue for readability)
hi Directory          guifg=#87cfff
hi NERDTreeOpenable   guifg=#87cfff
hi NERDTreeClosable   guifg=#87cfff
hi NERDTreeDirSlash   guifg=#87cfff
hi NERDTreeUp         guifg=#87cfff

" CoC error/warning highlights (colored text, no background)
hi CocErrorHighlight   guibg=NONE guifg=#f44747 gui=undercurl guisp=#f44747 cterm=underline ctermfg=Red
hi CocWarningHighlight guibg=NONE guifg=#cca700 gui=undercurl guisp=#cca700 cterm=underline ctermfg=Yellow
hi CocInfoHighlight    guibg=NONE guifg=#cca700 gui=undercurl guisp=#cca700 cterm=underline ctermfg=Yellow
hi CocHintHighlight    guibg=NONE guifg=#cca700 gui=undercurl guisp=#cca700 cterm=underline ctermfg=Yellow
hi CocUnusedHighlight  guibg=NONE guifg=#6b6b6b gui=undercurl guisp=#6b6b6b cterm=underline ctermfg=Grey
hi CocDeprecatedHighlight guibg=NONE gui=strikethrough guisp=#6b6b6b cterm=strikethrough
hi CocErrorLine        guibg=NONE
hi CocWarningLine      guibg=NONE

" Enums (match VSCode Visual Studio Dark)
hi Enum             guifg=#4ec9b0
hi CocSemEnum       guifg=#4ec9b0
hi CocSemEnumMember guifg=#4ec9b0
