" Light (Visual Studio) Vim color scheme
" Author: Converted from VS Code theme
" Usage: place this file in ~/.vim/colors/ and use :colorscheme light
" GENERATED by theme/generate.sh. Edit theme/palette.sh, not this file.
"
" Kept separate from nvim-light.tpl — see the note in vim-dark.tpl. Vim's
" statusline is a filled bar (green here, blue on dark: they never matched each
" other either) and its diffs tint the foreground over a pale wash, where Neovim
" colours the background.
"
" The duplicate Search and Visual lines below are in the original and are kept:
" harmless, and removing them is a change to a generated file's behaviour, not a
" palette question.

if exists("syntax_on")
  syntax reset
endif

set background=light
let g:colors_name = "vs_light"

" =====================
" Basic UI colors
" =====================
hi Normal       guifg=#000000 guibg=#fafafa
hi Cursor       guifg=#ffffff guibg=#000000
hi Visual       guibg=#add6ff
hi LineNr       guifg=#c0c0c0 guibg=#fafafa
hi CursorLineNr guifg=#999999 guibg=#fafafa
hi StatusLine   guifg=#ffffff guibg=#16825d
hi StatusLineNC guifg=#919191 guibg=#f3f3f3
hi VertSplit    guifg=#d4d4d4 guibg=#ffffff
hi Pmenu        guifg=#000000 guibg=#f3f3f3
hi PmenuSel     guifg=#ffffff guibg=#007acc
hi Search       guifg=#000000 guibg=#90c2f9
hi IncSearch    guifg=#000000 guibg=#add6ff

" =====================
" Comments
" =====================
hi Comment      guifg=#999999 gui=italic

" =====================
" Constants / Numbers / Booleans
" =====================
hi Constant     guifg=#0000ff
hi Number       guifg=#098658
hi Boolean      guifg=#098658
hi String       guifg=#a31515
hi Character    guifg=#811f3f

" =====================
" Identifiers
" =====================
hi Identifier   guifg=#0000ff
hi Function     guifg=#0451a5
hi Statement    guifg=#0000ff
hi Conditional  guifg=#0000ff
hi Repeat       guifg=#0000ff
hi Label        guifg=#0000ff
hi Operator     guifg=#000000
hi Keyword      guifg=#0000ff
hi Exception    guifg=#0000ff
hi PreProc      guifg=#0000ff
hi Include      guifg=#0000ff
hi Define       guifg=#0000ff
hi Macro        guifg=#0000ff
hi Type         guifg=#0451a5
hi StorageClass guifg=#0000ff
hi Structure    guifg=#0000ff
hi Typedef      guifg=#0451a5
hi Special      guifg=#800000
hi SpecialChar  guifg=#811f3f
hi Tag          guifg=#800000
hi Delimiter    guifg=#000000
hi SpecialComment guifg=#008000
hi Debug        guifg=#ff0000

" =====================
" Markdown / UI highlights
" =====================
hi Title        guifg=#800000 gui=bold
hi Bold         guifg=#000080 gui=bold
hi Italic       guifg=#0000ff gui=italic
hi Underlined   guifg=#0451a5 gui=underline
hi Todo         guifg=#a31515 guibg=NONE gui=bold

" =====================
" Diff / Git
" =====================
" Foreground-tinted over a pale wash, unlike Neovim's background-based diffs.
" The four washes are used once each, so they stay literal.
hi DiffAdd      guifg=#098658 guibg=#E8F8F5
hi DiffChange   guifg=#0451a5 guibg=#F0F0FF
hi DiffDelete   guifg=#a31515 guibg=#FFECEC
hi DiffText     guifg=#000000 guibg=#FFD700

" =====================
" CursorLine and Search
" =====================
hi CursorLine   guibg=#e5ebf1
hi Search       guibg=#90c2f9 guifg=#000000
hi Visual       guibg=#add6ff

" =====================
" Enums (match VSCode Visual Studio Light)
" =====================
hi Enum             guifg=#267f99
hi CocSemEnum       guifg=#267f99
hi CocSemEnumMember guifg=#267f99

" =====================
" End
" =====================
